"""add code to level model

Revision ID: ed7b6d30b2ea
Revises: 2b161ebc8324
Create Date: 2025-02-02 12:59:02.280551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed7b6d30b2ea'
down_revision = '2b161ebc8324'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('levels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(), nullable=False))
        batch_op.create_unique_constraint("uq_levels_code", ["code"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('levels', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('code')

    # ### end Alembic commands ###
